### PR TITLE
Inline Checkbox/Radio Fixes & Improvements

### PR DESCRIPTION
**Pull request by JerseyMilker**
Can't figure out how to make tests pass, sorry.

### CODE REVIEW

**Comment by JerseyMilker** [comment]
Just a thought... I wonder if changing API to something like this might make more sense, and also help with the mentioned rendering problem?  inline() as a chainable method, rather than inlineRadio() as a primary element method?
```
{!! BootForm::radio('Hidden', 'visibility', 'hidden')->inline()->check() !!}
{!! BootForm::checkbox('Hidden', 'visibility')->value('hidden')->inline()->check() !!}
```

**Comment by JerseyMilker** [comment]
I just pushed a few commits, which make the `inlineRadio()` and `inlineCheckbox()` tests pass.  This fixes my original issue with chainable methods appending to label instead of input control.

I also added a few new failing tests for that `inline()` as a chainable modifier idea I mentioned above.

**Comment by JerseyMilker** [comment]
Just noting that these tests will fail, specifically because these lines in the new [inline() chainable modifier](https://github.com/JerseyMilker/bootforms/blob/inline-radio-checkbox-chaining/src/AdamWathan/BootForms/Elements/CheckGroup.php#L37-L38) depends on [this PR on your base form package](https://github.com/adamwathan/form/pull/49).

Lastly, the old `inlineCheckbox()` and `inlineRadio()` methods are now just pass-throughs, and tell the new `inline()` modifier to do the heavy lifting (see this commit 0726a87).  I think inline as chainable modifier makes more sense API wise, but these passthroughs keep the package backwards compatible.  All of the following should now be valid:
```php
{!! BootForm::radio('Hidden', 'visibility')->inline() !!}
{!! BootForm::checkbox('Hidden', 'visibility')->inline() !!}

{!! BootForm::inlineRadio('Hidden', 'visibility') !!}
{!! BootForm::inlineCheckbox('Hidden', 'visibility') !!}
```

My only concern right now is that I removed this behaviour from `inlineCheckbox()`:
```php
if ($checked) {
    $control->check();
} else {
    $control->uncheck();
}
```
I assume this is already handled by non-inline `checkbox()`, but I should probably double check for `checkbox()->inline()`.

**Comment by adamwathan** [comment]
Can you update your code to use `getAttribute('type')` instead of the `type` method? I had to remove that method from the base form package because of a collision with the `InputGroup` element in this package. Those shorthand methods are traditionally setters in these packages anyways so it made more sense to me to add a different method for getting attribute values.

**Comment by JerseyMilker** [comment]
For sure, I'll take a look at this when I have chance.

**Comment by JerseyMilker** [comment]
Done.

**Comment by JerseyMilker** [comment]
Hugs for everyone.

**Comment by JerseyMilker** [comment]
Hey @adamwathan, I just realized commit a39cc97 requires adamwathan/form 0.7.1 or greater.  You have `0.7.*` in composer.json.

**Comment by adamwathan** [comment]
Sounds like an opportunity for a pull request.

**Pull request merged**
