### PR TITLE
Allow targeting different pieces of a form group

### PR DESCRIPTION
**Pull request by adamwathan**

### CODE REVIEW

**Comment by Sobak** [comment]
Excellent idea! So flexible and yet simple.

**Comment by adamwathan** [comment]
@Sobak convinced me to merge :)

**Comment by Sobak** [comment]
Thank you - I will definitely use it in my project. Shouldn't be b85360 reverted now?

Also, I'll try to work on README/documentation in next few days, but I can't promise anything.

**Comment by adamwathan** [comment]
@Sobak I think it's fine to keep both, the other functions can be helpful for really common stuff and save a method call, not too worried about the surface area of this API.

Would be awesome if you could get some updates into the docs, would be greatly appreciated!

**Pull request merged**
